config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :valentines

end

app/models/valentine.rb
class Valentine < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/valentines_controller.rb
class ValentinesController < ApplicationController

  def new
    @valentine = Valentine.new
  end

  def create
    @valentine = Valentine.new(valentine_params)

    if @valentine.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def valentine_params
    params.require(:valentine).permit(:from, :message)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ValentinesDay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>

app/views/valentines/new.html.erb
<div class='form'>
  <%= form_for @valentine do |f| %>

  <div class='from'>
    <%= f.label "From" %>
  </div>


  <div class='from-text'>
    <%= f.text_field :from %>
  </div>


  <div class='message'>
    <%= f.label "Message" %>
  </div>


  <div class='message-text'>
    <%= f.text_area :message, height: "76", width: "182" %>
  </div>

    <br>

  <div class='button'>
    <%= f.submit "Send the Love" %>
  </div>

  <% end %>
</div>

app/views/welcome/index.html.erb
<div class='welcome'>
  <h1>Welcome!</h1>
</div>


<div class='link'>
  <%= link_to "Send Shelby a Valentine!", new_valentine_path %>
</div>